services:
  traefik:
    image: "traefik:v3.0"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "80:80"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  app:
    # set container name app
    container_name: app
    image: vicous/t-clo-app-prod:latest
    ports:
      - "8081:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: $DB_CONNECTION
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=HostRegexp(`.*`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

