services:
  traefik:
    image: "traefik:v3.0"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "80:80"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  app:
    # set container name app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=HostRegexp(`.*`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

    command: >
      sh -c "until php -r 'new PDO(\"mysql:host=db;port=3306;dbname=app_database\", \"app_user\", \"app_password\");' 2>/dev/null; do
        echo 'Waiting for DB...'; sleep 2;
      done;
      php artisan migrate --force;
      exec apache2-foreground"
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
      MYSQL_TCP_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # Permet d'exécuter des scripts SQL initiaux
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  db_data:
