version: "3.9"

services:
  consul:
    image: hashicorp/consul:1.18.0
    container_name: consul-server
    ports:
      - "8500:8500"   # HTTP API / Web UI
      - "8600:8600/udp" # DNS interface
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data
    restart: unless-stopped

volumes:
  consul-data:
