# Playbook to initialize a server with necessary packages and configurations
---
- name: Install docker service
  hosts: all
  become: yes
  roles:
    - install-docker

- name: Deploy Database Server
  hosts: databases
  become: yes
  vars_files:
    - roles/group_vars/all.yml
  roles:
    - deploy-database

#- name: Deploy Web Server
#  hosts: webservers
#  become: yes
#  vars_files:
#    - roles/group_vars/all.yml
#  roles:
#    - deploy-webserver