name: MAIN

on:

  push:
    branches: [ main ]

jobs:
    docker-build-and-push:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build Docker image
        workdir: ./sample-app-master
        run: |
          docker build -f Dockerfile -t ghcr.io/t-clo-epitech/app-prod:latest ./

      - name: Push Docker image
        run: |
          docker push ghcr.io/T-CLO-Epitech/app-prod:latest