name: Terraform Destroy Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to destroy'
        required: true
        default: 'v1.0.0'

jobs:
  terraform-destroy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Export Azure Service Principal creds
        run: |
          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS_PROD).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS_PROD).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS_PROD).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS_PROD).tenantId }}" >> $GITHUB_ENV

      - name: Destroy Prod VM
        working-directory: infra
        run: |
          terraform init -backend-config="path=terraform/prod"
          terraform destroy -auto-approve -var-file="prod.tfvars"

